const campaignTemplateDefinitions = [
  {
    id: "CAMPAIGN-TEMPLATE-PRODUCT-LAUNCH",
    name: "Product launch campaign",
    recordType: "campaign",
    appliesTo: "Product Launch",
    isDefault: true,
    defaults: {
      campaignType: "Product Launch",
      status: "draft",
    },
  },
  {
    id: "CAMPAIGN-TEMPLATE-EMAIL-NURTURE",
    name: "Email nurture campaign",
    recordType: "campaign",
    appliesTo: "Email Nurture",
    isDefault: true,
    defaults: {
      campaignType: "Email Nurture",
      status: "draft",
    },
  },
];

export const CONTENT_BUILDER_OPTIONS = {
  itemTypes: [
    "tool",
    "clinical supply",
    "exercise equipment",
    "course",
    "faq",
    "workshop",
    "content",
    "part",
    "program",
    "anato-me",
    "policy",
    "event",
    "outcome measure",
  ],
  itemKinds: [
    "Shop Product",
    "Reference Item",
    "Clinical Test Item",
    "Asset",
    "Policy",
    "Session",
    "Part",
    "Standard",
  ],
  categoryOptions: [
    { id: "CAT-ART", name: "Active Recovery Technique" },
    { id: "CAT-TEST", name: "Clinical Test" },
    { id: "CAT-TREAT", name: "Treatment Technique" },
    { id: "CAT-CLEDU", name: "Client Education" },
    { id: "CAT-THEREDU", name: "Therapist Education" },
    { id: "CAT-ERGO", name: "Ergonomics" },
    { id: "CAT-BUS-CONT", name: "Business Content" },
    { id: "CAT-PRESENTATION", name: "Client Presentation" },
    { id: "CAT-NEURODYNAMIC", name: "Neurodynamic" },
  ],
  blueprintTypes: [
    "recovery activity",
    "clinical test",
    "treatment technique",
    "client education",
    "anato-me story",
    "quiz",
    "therapist education",
    "business workflow",
    "marketing content",
    "product manufacture",
  ],
  planTypes: [
    "course",
    "workshop",
    "treatment plan",
    "assessment",
    "reassessment",
    "business manual",
    "recovery plan",
    "business workflow",
    "campaign",
  ],
  campaignTypes: [
    "Condition Education",
    "Product Launch",
    "Course Launch",
    "Workshop Promotion",
    "Evergreen Education",
    "Seasonal Campaign",
    "Awareness Campaign",
    "Affiliate Campaign",
    "Creator Campaign",
    "Community Campaign",
    "Internal Campaign",
  ],
  contentStatuses: ["draft", "review", "active", "paused", "archived"],
  visibilityValues: ["private", "users", "affiliates", "therapists", "admin", "unlocked"],
  templateDefinitions: {
    item: [],
    blueprint: [],
    plan: [],
    campaign: campaignTemplateDefinitions,
  },
  statuses: ["draft", "review", "active", "paused", "archived"],
};
