const itemTemplateDefinitions = [
  {
    id: "ITEM-TEMPLATE-SHOP-PHYSICAL-PRODUCT",
    name: "Shop physical product",
    recordType: "item",
    appliesTo: "Physical Product",
    isDefault: true,
    defaults: {
      firebaseType: "tool",
      itemType: "Physical Product",
      itemKind: "Shop Product",
      categoryId: "CAT-TREAT",
      isShopProduct: true,
      requiresShipping: true,
      inventoryTracked: true,
      stockStatus: "draft",
      soldByRecoveryTools: true,
    },
  },
  {
    id: "ITEM-TEMPLATE-REFERENCE-PHYSICAL-ITEM",
    name: "Reference physical item",
    recordType: "item",
    appliesTo: "Physical Product",
    defaults: {
      firebaseType: "tool",
      itemType: "Physical Product",
      itemKind: "Reference Item",
      categoryId: "CAT-ART",
      isShopProduct: false,
      requiresShipping: false,
      inventoryTracked: false,
      stockStatus: "not-tracked",
      soldByRecoveryTools: false,
    },
  },
  {
    id: "ITEM-TEMPLATE-CLINICAL-TEST-ITEM",
    name: "Clinical test item",
    recordType: "item",
    appliesTo: "Physical Product",
    defaults: {
      firebaseType: "clinical supply",
      itemType: "Physical Product",
      itemKind: "Clinical Test Item",
      categoryId: "CAT-TEST",
      isShopProduct: false,
      requiresShipping: false,
      inventoryTracked: false,
      stockStatus: "not-tracked",
      soldByRecoveryTools: false,
    },
  },
  {
    id: "ITEM-TEMPLATE-DIGITAL-COURSE",
    name: "Digital course",
    recordType: "item",
    appliesTo: "Digital Product",
    isDefault: true,
    defaults: {
      firebaseType: "course",
      itemType: "Digital Product",
      itemKind: "Digital Product",
      categoryId: "CAT-CLEDU",
      isShopProduct: true,
      requiresShipping: false,
      inventoryTracked: false,
      stockStatus: "not-tracked",
      soldByRecoveryTools: true,
      unlocksAccess: true,
      accessType: "Course",
    },
  },
  {
    id: "ITEM-TEMPLATE-PDF-DOWNLOAD",
    name: "PDF download",
    recordType: "item",
    appliesTo: "Digital Product",
    defaults: {
      firebaseType: "document",
      itemType: "Digital Product",
      itemKind: "Asset",
      categoryId: "CAT-CLEDU",
      isShopProduct: true,
      requiresShipping: false,
      inventoryTracked: false,
      stockStatus: "not-tracked",
      soldByRecoveryTools: true,
    },
  },
  {
    id: "ITEM-TEMPLATE-SESSION",
    name: "Session / workshop / webinar",
    recordType: "item",
    appliesTo: "Session",
    isDefault: true,
    defaults: {
      firebaseType: "workshop",
      itemType: "Session",
      itemKind: "Session",
      categoryId: "CAT-CLEDU",
      isShopProduct: true,
      requiresShipping: false,
      inventoryTracked: false,
      stockStatus: "not-tracked",
      soldByRecoveryTools: true,
      accessType: "Workshop",
      requiresCalendar: true,
      requiresSessionTime: true,
      tracksSeats: true,
    },
  },
  {
    id: "ITEM-TEMPLATE-WEBINAR",
    name: "Webinar",
    recordType: "item",
    appliesTo: "Session",
    defaults: {
      firebaseType: "workshop",
      itemType: "Session",
      itemKind: "Session",
      categoryId: "CAT-THEREDU",
      isShopProduct: true,
      requiresShipping: false,
      inventoryTracked: false,
      stockStatus: "not-tracked",
      soldByRecoveryTools: true,
      accessType: "Workshop",
      requiresCalendar: true,
      requiresSessionTime: true,
      tracksSeats: true,
      deliveryMode: "online",
    },
  },
  {
    id: "ITEM-TEMPLATE-POLICY-DOCUMENT",
    name: "Policy / business document",
    recordType: "item",
    appliesTo: "Digital Product",
    defaults: {
      firebaseType: "policy",
      itemType: "Digital Product",
      itemKind: "Policy",
      categoryId: "CAT-BUS-CONT",
      isShopProduct: false,
      requiresShipping: false,
      inventoryTracked: false,
      stockStatus: "not-tracked",
      soldByRecoveryTools: true,
    },
  },
];

const blueprintTemplateDefinitions = [
  {
    id: "BT-EX-HOWTO",
    name: "Exercise How-To",
    recordType: "blueprint",
    appliesTo: "Recovery Activity",
    isDefault: true,
    defaults: {
      blueprintTemplateId: "BT-EX-HOWTO",
      blueprintType: "Recovery Activity",
      ownerType: "Recovery Tools",
      approvalStatus: "Draft",
      visibility: "Private",
    },
  },
];

const planTemplateDefinitions = [
  {
    id: "PTV-EX-30",
    name: "30 min Exercise Plan",
    recordType: "plan",
    appliesTo: "Exercise Plan",
    isDefault: true,
    defaults: {
      planTemplateId: "PT-EXERCISE",
      templateVariantId: "PTV-EX-30",
      planType: "Exercise Plan",
      durationMinutes: 30,
      sizeLabel: "Standard",
    },
  },
  {
    id: "PTV-EX-60",
    name: "60 min Exercise Plan",
    recordType: "plan",
    appliesTo: "Exercise Plan",
    defaults: {
      planTemplateId: "PT-EXERCISE",
      templateVariantId: "PTV-EX-60",
      planType: "Exercise Plan",
      durationMinutes: 60,
      sizeLabel: "Standard",
    },
  },
  {
    id: "PTV-RECOVERY-ONLY",
    name: "Recovery only plan",
    recordType: "plan",
    appliesTo: "Exercise Plan",
    defaults: {
      planTemplateId: "PT-EXERCISE",
      templateVariantId: "PTV-RECOVERY-ONLY",
      planType: "Exercise Plan",
      durationMinutes: 30,
      sizeLabel: "Recovery only",
    },
  },
];

const campaignTemplateDefinitions = [
  {
    id: "CAMPAIGN-TEMPLATE-PRODUCT-LAUNCH",
    name: "Product launch campaign",
    recordType: "campaign",
    appliesTo: "Product Launch",
    isDefault: true,
    defaults: {
      campaignType: "Product Launch",
      status: "draft",
    },
  },
  {
    id: "CAMPAIGN-TEMPLATE-EMAIL-NURTURE",
    name: "Email nurture campaign",
    recordType: "campaign",
    appliesTo: "Email Nurture",
    isDefault: true,
    defaults: {
      campaignType: "Email Nurture",
      status: "draft",
    },
  },
];

export const CONTENT_BUILDER_OPTIONS = {
  itemTypes: [
    "Physical Product",
    "Digital Product",
    "Session",
  ],
  itemKinds: [
    "Shop Product",
    "Reference Item",
    "Clinical Test Item",
    "Asset",
    "Policy",
    "Session",
    "Part",
    "Standard",
  ],
  categoryOptions: [
    { id: "CAT-ART", name: "Active Recovery Technique" },
    { id: "CAT-TEST", name: "Clinical Test" },
    { id: "CAT-TREAT", name: "Treatment Technique" },
    { id: "CAT-CLEDU", name: "Client Education" },
    { id: "CAT-THEREDU", name: "Therapist Education" },
    { id: "CAT-ERGO", name: "Ergonomics" },
    { id: "CAT-BUS-CONT", name: "Business Content" },
    { id: "CAT-PRESENTATION", name: "Client Presentation" },
    { id: "CAT-NEURODYNAMIC", name: "Neurodynamic" },
  ],
  firebaseTypes: [
    "tool",
    "clinical supply",
    "exercise equipment",
    "course",
    "workshop",
    "content",
    "document",
    "part",
    "policy",
    "standards",
  ],
  blueprintTypes: [
    "Exercise",
    "Test",
    "Treatment",
    "Education",
    "Lesson",
    "Assessment",
    "Outcome Measure",
    "Business Workflow",
    "Marketing Content",
    "Recovery Activity",
  ],
  planTypes: [
    "Exercise Plan",
    "Treatment Plan",
    "Recovery Plan",
    "Assessment",
    "Reassessment",
    "Course",
    "Workshop",
    "Program",
    "Session",
    "Testing Bundle",
    "Recovery Tools Business Operations",
  ],
  campaignTypes: [
    "Condition Education",
    "Product Launch",
    "Course Launch",
    "Workshop Promotion",
    "Evergreen Education",
    "Seasonal Campaign",
    "Awareness Campaign",
    "Affiliate Campaign",
    "Creator Campaign",
    "Community Campaign",
    "Internal Campaign",
  ],
  contentStatuses: ["draft", "active", "paused", "archived"],
  publishStatuses: ["unpublished", "scheduled", "published", "unlisted", "removed"],
  approvalStatuses: [
    "not submitted",
    "pending review",
    "changes requested",
    "approved",
    "rejected",
    "archived",
  ],
  visibilityValues: ["private", "system", "marketplace", "public", "unlisted"],
  templateDefinitions: {
    item: itemTemplateDefinitions,
    blueprint: blueprintTemplateDefinitions,
    plan: planTemplateDefinitions,
    campaign: campaignTemplateDefinitions,
  },
  statuses: ["draft", "active", "review", "archived"],
};
